### PR TITLE
Update chrono, bump version

### PR DESCRIPTION
**Pull request by alexbool**

### CODE REVIEW

**Comment by 0xpr03** [comment]
Please also add the re-exports. Currently we're not able to use timer as of chrono's change in re-exporting chrono::datetime::DateTime (now private) to chrono::DateTime

**Comment by 0xpr03** [comment]
Chrono is now on 0.4

**Comment by Yoric** [comment]
My apologies, I hadn't seen this PR.

@alexbool Do you want to resolve the conflict so that I can push it?

**Comment by 0xpr03** [comment]
This is overhauled by #8, as #8 is using 0.4 and this one upgrades to 0.3

**Comment by Yoric** [comment]
Well, @alexbool 's code also replaces `-` by `signed_duration_since`. I figure this is worth landing.

**Comment by 0xpr03** [comment]
Ah, missed that one.

**Pull request closed without merging**
