### PR TITLE
trait objects without an explicit `dyn` are deprecated

### PR DESCRIPTION
**Pull request by luisbg**
There are more of these in the code. I am sending the fix for one just to check if this is accepted.

### CODE REVIEW

**Comment by 0xpr03** [comment]
Does this affect the minimum rust version ?

**Comment by luisbg** [comment]
Not unless you go way back. It was introduced in 2017.

https://github.com/rust-lang/rfcs/blob/master/text/2113-dyn-trait-syntax.md

**Comment by luisbg** [comment]
I just noticed your repo is not in Hacktoberfest.

Can you add the `hacktoberfest-accepted` label to this PR?

**Review by Yoric — APPROVED** [review]
Thanks!

**Comment by luisbg** [comment]
😄

**Pull request merged**
